name: Build macOS Executable (English)

on:
  push:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: 1. Baixar o código do seu repositório
      uses: actions/checkout@v4

    - name: 2. Configurar o ambiente Python no Mac
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Instalar o FFmpeg
      run: brew install ffmpeg

    - name: 4. Instalar as bibliotecas do requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    ### CORREÇÃO APLICADA AQUI ###
    - name: 5. Instalar o PyInstaller separadamente
      run: pip install pyinstaller

    - name: 6. Criar o executável com PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-binary "$(which ffmpeg):." --name "GeradorDeAudioEN" gerador_en_gui.py

    - name: 7. Disponibilizar o .app para download
      uses: actions/upload-artifact@v4
      with:
        name: GeradorDeAudioEN-macOS
        path: dist/GeradorDeAudioEN.app
